name: Deploy Svelte Static Site to GitHub Pages

on:
  push:
    branches:
      - master  # o 'master', a seconda del nome del tuo branch principale

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # Specifichiamo dove si trova il package-lock.json per la cache
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        # <<< LA PRIMA MODIFICA CHIAVE >>>
        # Esegui questo comando DENTRO la cartella /frontend
        working-directory: ./frontend

      - name: Build static site
        # Passiamo la variabile d'ambiente per il base path
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          PUBLIC_BACKEND_URL: 'https://vfansss.eu.pythonanywhere.com'
        run: npm run build
        # <<< LA SECONDA MODIFICA CHIAVE >>>
        # Esegui anche la build DENTRO /frontend
        working-directory: ./frontend

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          # <<< LA TERZA MODIFICA CHIAVE >>>
          # Il percorso dell'artefatto è ora relativo alla root,
          # quindi puntiamo a `frontend/build`
          path: 'frontend/build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4